export const carouselCar = [
  {
    title: "You can buy Sleek & Innovative Audi Car",
    description:
      "German engineering, known for luxury and advanced technology.",
    image: "/carousel/audi.png",
  },
  {
    title: "You can buy Performance Icon Porsche",
    description:
      "Synonymous with high-performance sports cars and distinctive design.",
    image: "/carousel/porshce.png",
  },
  {
    title: "You can buy Opulent Elegance Roll royce",
    description: "The pinnacle of luxury, offering bespoke craftsmanship.",
    image: "/carousel/rollroice.png",
  },
  {
    title: "You can buy Dynamic Precision BMW",
    description:
      "Renowned for sporty performance and executive class vehicles.",
    image: "/carousel/bmw.png",
  },
  {
    title: "You can buy Exotic Mastery Hyundai Car",
    description:
      "Italian boutique manufacturer of hypercars known for exclusivity.",
    image: "/carousel/hyundai.png",
  },
  {
    title: "You can buy Electric Revolution Car",
    description: "Leading the charge in electric mobility and innovation.",
    image: "/carousel/tesla.png",
  },
];

export const mockCar = [
  {
    id: 1,
    category: "Car",
    slug: "hyundai-avante-blue-2021-1",
    sellerCity: "Addis Ababa",
    sellerStreet: "Bole Medhanialem",
    images: [
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680103_MTYwMC04MjMtMTlmNGUzMmEwYy0x_xpvjq0.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/bmw-m3-gtr-street-si_chwvv8.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680105_MTYwMC05MzUtNzVkOGFkYzkwMS0x_bujywd.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680100_MTYwMC0xMDU5LTliZmMzYWYyNDUtMQ_kl4okl.webp",      
    ],
    make: "Hyundai",
    model: "Avante",
    yearOfManufacture: 2021,
    color: "Blue",
    interiorColor: "Black",
    condition: "Foreign Used",
    transmission: "Automatic",
    keyFeatures: [
      "Radio",
      "Air Conditioning",
      "Bluetooth Connectivity",
      "Heated Seats",
      "Reverse Parking Sensors",
      "Sunroof",
    ],
    isCarRegistered: true,
    body: "Sedan",
    fuel: "Petrol",
    mileage: 38000,
    seats: 5,
    numberOfCylinders: 4,
    engineSize: "1.6L",
    horsePower: 150,
    description:
      "A reliable and well-maintained foreign used Hyundai Avante. Excellent fuel efficiency and a smooth driving experience. The car is in pristine condition with no accidents or damages. It’s perfect for both city commuting and long drives.",
    price: 18500,
    negotiationAvailable: true,
    phoneNumber: "+251919298886",
    payment: "Silver",
  },
  {
    id: 2,
    category: "Car",
    slug: "toyota-corolla-white-2018-2",
    sellerCity: "Addis Ababa",
    sellerStreet: "Lideta, Near Lion Hotel",
    images: [
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680103_MTYwMC04MjMtMTlmNGUzMmEwYy0x_xpvjq0.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/bmw-m3-gtr-street-si_chwvv8.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680105_MTYwMC05MzUtNzVkOGFkYzkwMS0x_bujywd.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680100_MTYwMC0xMDU5LTliZmMzYWYyNDUtMQ_kl4okl.webp",
    ],
    make: "Toyota",
    model: "Corolla",
    yearOfManufacture: 2018,
    color: "White",
    interiorColor: "Gray",
    condition: "Local Used",
    transmission: "Manual",
    mileage: 38000,
    keyFeatures: [
      "Bluetooth Connectivity",
      "Air Conditioning",
      "Power Windows",
      "ABS",
      "Cruise Control",
    ],
    isCarRegistered: true,
    body: "Sedan",
    fuel: "Petrol",
    seats: 5,
    numberOfCylinders: 4,
    engineSize: "1.8L",
    horsePower: 140,
    description:
      "A well-maintained Toyota Corolla, locally used, with excellent mileage and performance. Ideal for family use and daily commuting in Addis Ababa.",
    price: 12500,
    negotiationAvailable: false,
    phoneNumber: "+251919298886",
    payment: "Gold",
  },
  {
    id: 3,
    category: "Car",
    slug: "Mercedes-Benz-C-Class-silver-2020-3",
    sellerCity: "Addis Ababa",
    sellerStreet: "Kazanchis, Near the African Union",
    images: [
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680103_MTYwMC04MjMtMTlmNGUzMmEwYy0x_xpvjq0.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/bmw-m3-gtr-street-si_chwvv8.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680105_MTYwMC05MzUtNzVkOGFkYzkwMS0x_bujywd.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680100_MTYwMC0xMDU5LTliZmMzYWYyNDUtMQ_kl4okl.webp",
    ],
    make: "Mercedes-Benz",
    model: "C-Class",
    yearOfManufacture: 2020,
    mileage: 38000,
    color: "Silver",
    interiorColor: "Beige",
    condition: "Foreign Used",
    transmission: "Automatic",
    keyFeatures: [
      "Leather Seats",
      "Navigation System",
      "Rearview Camera",
      "Bluetooth Connectivity",
      "Sunroof",
    ],
    isCarRegistered: true,
    body: "Sedan",
    fuel: "Petrol",
    seats: 5,
    numberOfCylinders: 6,
    engineSize: "2.0L",
    horsePower: 200,
    description:
      "A luxurious Mercedes-Benz C-Class, foreign used, offering both comfort and performance. It’s a great choice for anyone looking for a high-end ride in excellent condition.",
    price: 35000,
    negotiationAvailable: true,
    phoneNumber: "+251919298886",
    payment: "Platinum",
  },
  {
    id: 4,
    category: "Car",
    slug: "nissan-x-trial-black-2019-4",
    sellerCity: "Addis Ababa",
    sellerStreet: "Megenagna, Near the Police Station",
    images: [
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680103_MTYwMC04MjMtMTlmNGUzMmEwYy0x_xpvjq0.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/bmw-m3-gtr-street-si_chwvv8.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680105_MTYwMC05MzUtNzVkOGFkYzkwMS0x_bujywd.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680100_MTYwMC0xMDU5LTliZmMzYWYyNDUtMQ_kl4okl.webp",
    ],
    make: "Nissan",
    model: "X-Trail",
    yearOfManufacture: 2019,
    mileage: 38000,
    color: "Black",
    interiorColor: "Dark Gray",
    condition: "Foreign Used",
    transmission: "CVT",
    keyFeatures: [
      "4WD",
      "Air Conditioning",
      "Bluetooth Connectivity",
      "Heated Seats",
      "Roof Rack",
    ],
    isCarRegistered: true,
    body: "SUV",
    fuel: "Petrol",
    seats: 5,
    numberOfCylinders: 4,
    engineSize: "2.5L",
    horsePower: 180,
    description:
      "A spacious and reliable Nissan X-Trail, perfect for Ethiopian roads. It offers great performance both in the city and off-road. Well maintained and in excellent condition.",
    price: 25000,
    negotiationAvailable: true,
    phoneNumber: "+251919298886",
    payment: "Silver",
  },
  {
    id: 5,
    slug: "kia-sportage-red-2022-5",
    category: "Car",
    sellerCity: "Addis Ababa",
    sellerStreet: "Bole, Next to the Airport",
    images: [
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680103_MTYwMC04MjMtMTlmNGUzMmEwYy0x_xpvjq0.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/bmw-m3-gtr-street-si_chwvv8.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680105_MTYwMC05MzUtNzVkOGFkYzkwMS0x_bujywd.webp",
      "https://res.cloudinary.com/dg6ck04nm/image/upload/kachamale/5680100_MTYwMC0xMDU5LTliZmMzYWYyNDUtMQ_kl4okl.webp",
    ],
    make: "Kia",
    model: "Sportage",
    yearOfManufacture: 2022,
    mileage: 38000,
    color: "Red",
    interiorColor: "Tan",
    condition: "Brand New",
    transmission: "Automatic",
    keyFeatures: [
      "Heated Seats",
      "Bluetooth Connectivity",
      "Rearview Camera",
      "Touchscreen Display",
      "Alloy Wheels",
    ],
    isCarRegistered: true,
    body: "SUV",
    fuel: "Petrol",
    seats: 5,
    numberOfCylinders: 4,
    engineSize: "2.0L",
    horsePower: 160,
    description:
      "A brand-new Kia Sportage, ideal for family outings and adventurous road trips in Ethiopia. It combines modern design with advanced features for a comfortable ride.",
    price: 30000,
    negotiationAvailable: false,
    phoneNumber: "+251919298886",
    payment: "Gold",
  },
];

export const users = [
  {
    id: 1,
    profile: "https://cdn-icons-png.freepik.com/256/1077/1077114.png?semt=ais_hybrid",
    fullName: "John Doe",
    email: "john@gmail.com",
    phoneNumber: "+251919298886",
  }
]
